name: 🚀 Deploy to FullTimberStack.dev

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📂 Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to FullTimberStack
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./        # or ./ if deploying root
          server-dir: public_html/  # WHH default
